// SPDX-FileCopyrightText: David Cabot <d-k-bo@mailbox.org>
// SPDX-License-Identifier: GPL-3.0-or-later

//! Parser for the channel lists generated by the FRITZ!Box (`/dvb/m3u/*.m3u`).
//!
//! Each entry consists of an `#EXTINF:0,<name>` line, an optional
//! `#EXTVLCOPT:…` line and the `rtsp://` URL of the channel.

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FritzChannel {
    pub name: String,
    pub url: String,
}

/// Returns `true` if `text` is an (possibly empty) M3U playlist and not e.g. a
/// HTML login page.
pub fn is_playlist(text: &str) -> bool {
    let text = text.trim_start_matches('\u{feff}').trim_start();
    text.is_empty() || text.starts_with("#EXTM3U")
}

pub fn parse(text: &str) -> Vec<FritzChannel> {
    let mut channels = Vec::new();
    let mut name: Option<String> = None;

    for line in text.trim_start_matches('\u{feff}').lines() {
        let line = line.trim();

        if let Some(info) = line.strip_prefix("#EXTINF:") {
            // `#EXTINF:<duration>[ <attributes>],<name>`
            name = info
                .split_once(',')
                .map(|(_, name)| name.trim().to_owned())
                .filter(|name| !name.is_empty());
        } else if line.is_empty() || line.starts_with('#') {
            continue;
        } else {
            channels.push(FritzChannel {
                name: name.take().unwrap_or_else(|| line.to_owned()),
                url: line.to_owned(),
            });
        }
    }

    channels
}

/// Decodes the playlist as UTF-8, falling back to ISO-8859-1.
pub fn decode(bytes: &[u8]) -> String {
    match std::str::from_utf8(bytes) {
        Ok(text) => text.to_owned(),
        Err(_) => bytes.iter().copied().map(char::from).collect(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const PLAYLIST: &str = "#EXTM3U\n\
        #EXTINF:0,ZDF HD\n\
        #EXTVLCOPT:network-caching=1000\n\
        rtsp://192.168.178.1:554/?avm=1&freq=450&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=1&pids=0,16,17,18,20,6100,6110,6120,6121,6123,6130,6131,6170\n\
        #EXTINF:0,BR Fernsehen Süd HD\n\
        #EXTVLCOPT:network-caching=1000\n\
        rtsp://192.168.178.1:554/?avm=1&freq=338&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=1&pids=0,16,17,18,20,5200,5201,1076,1570,2171,5202,5203,5204,5205\n";

    #[test]
    fn parses_fritzbox_playlist() {
        let channels = parse(PLAYLIST);

        assert_eq!(channels.len(), 2);
        assert_eq!(channels[0].name, "ZDF HD");
        assert!(channels[0]
            .url
            .starts_with("rtsp://192.168.178.1:554/?avm=1&freq=450"));
        assert_eq!(channels[1].name, "BR Fernsehen Süd HD");
        assert!(channels[1].url.ends_with("5204,5205"));
    }

    #[test]
    fn tolerates_missing_options_crlf_and_bom() {
        let channels = parse(
            "\u{feff}#EXTM3U\r\n#EXTINF:0,Bremen Vier\r\nrtsp://192.168.178.1:554/?avm=1&freq=410\r\n\r\nrtsp://192.168.178.1:554/?avm=1&freq=330\r\n",
        );

        assert_eq!(
            channels,
            [
                FritzChannel {
                    name: "Bremen Vier".to_owned(),
                    url: "rtsp://192.168.178.1:554/?avm=1&freq=410".to_owned(),
                },
                FritzChannel {
                    name: "rtsp://192.168.178.1:554/?avm=1&freq=330".to_owned(),
                    url: "rtsp://192.168.178.1:554/?avm=1&freq=330".to_owned(),
                },
            ]
        );
    }

    #[test]
    fn detects_playlists() {
        assert!(is_playlist(PLAYLIST));
        assert!(is_playlist(""));
        assert!(is_playlist("\u{feff}#EXTM3U\n"));
        assert!(!is_playlist("<!DOCTYPE html><html>"));
    }

    #[test]
    fn decodes_latin1_fallback() {
        assert_eq!(decode("Süd".as_bytes()), "Süd");
        assert_eq!(decode(b"S\xfcd"), "Süd");
    }
}
